version: '3'

services:
  nats-streaming:
    image: "nats-streaming:latest"
    restart: always
    ports:
      - 4223:4222
      - 8222:8222
    volumes:
      - ./etc/nats.conf:/nats.conf
    command: ['-c', '/nats.conf']

  mongodb:
    image: "mongo:3.6.3"
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
    ports:
      - 27018:27017
